name=MiniNeoPixels
version=1.0.0
author=Felix Ochoa
maintainer=Felix Ochoa
sentence=A lightweight library that wraps around Adafruit_NeoPixel to provide simple methods to control WS2812 LEDs.
paragraph=Provides simple methods to control WS2812 LEDs.
category=Sensors
url=https://github.com/felixthecat8a/MiniNeoPixels
architectures=*
includes=Adafruit_NeoPixel.h
